version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - app
        container_name: blog_aggregation_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: blog_aggregation_app

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: blog_aggregation
            MYSQL_ROOT_PASSWORD: 12345678
        volumes:
            - ./tmp/db:/var/lib/mysql
        container_name: blog_aggregation_db

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db
        container_name: blog_aggregation_adminer
